name: github-to-biotools converter
description: Convert a repo's metadata into biotools format and create a link

inputs:
  repo_id:
    description: id of this repo
    required: true
  owner_id:
    description: id of the owner
    required: true
  biotools_id:
    description: id on biotools if it exists
    required: false

outputs:
  url:
    description: URL to create/update this tool in bio.tools

runs:
  using: "composite"
  steps:
    - name: checkout CLI
      uses: actions/checkout@v5
      with:
        repository: bio-tools/biohackathon2025
        ref: generate_bt
    - name: install CLI
      shell: bash
      run: |
        pipx install poetry
        # install (all groups)
        poetry install
    - name: run the converter
      shell: bash
      run: |
        result=$(poetry run bridge cli github-to-biotools extract ${{ inputs.owner_id }} ${{ inputs.repo_id }})
        echo $result
        echo "***this is a test!***"
        echo $result
