name: github-to-biotools converter
description: Convert a repo's metadata into biotools format and create a link

inputs:
  repo_id:
    description: id of this repo
    required: true
  owner_id:
    description: id of the owner
    required: true
  biotools_id:
    description: id on biotools if it exists
    required: false

outputs:
  url:
    description: URL to create/update this tool in bio.tools

runs:
  using: "composite"
  steps:
    - name: download and install CLI
      shell: bash
      run: |
        git clone git@github.com:bio-tools/biohackathon2025.git
        cd biohackathon2025

        # install (all groups)
        poetry install
    - name: output token start
      shell: bash
      run: |
        echo "start"
        echo $GITHUB_TOKEN | cut -i1-3
        echo "end"
    - name: run the converter help
      shell: bash
      run: |
        which poetry
        poetry run bridge cli --help
